---
backglassChecksum: "7CA17F28DB840C375A42B9C9A38C3365"
backglassVPSId: "8fhRoYAcwm"
fps: 60
romChecksum: "8C763B7C6708184D432ED534CA88E2C2"
romVPSId: "c1x_esE7"
tableVPSId: "OMbYnBpl"
tagline: "Become a tycoon... Like me!"
testers:
  - "CoffeeAtJoes"
  - "Miku"
vpxChecksum: "DFFF7A5BB6FC2772FC0A39FA3CC4086A"
vpxVPSId: "0QKuh222t-"
